# Generated by Django 4.1.3 on 2022-11-30 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scans',
            fields=[
                ('url', models.URLField(blank=True, db_index=True, max_length=150)),
                ('ip', models.GenericIPAddressField()),
                ('date_time', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('is_private', models.BooleanField(default=False)),
                ('client_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='evaluator.leads')),
            ],
        ),
    ]
