# Generated by Django 4.1.3 on 2022-11-30 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leads',
            new_name='Lead',
        ),
        migrations.RenameModel(
            old_name='Scans',
            new_name='Scan',
        ),
    ]
