# Generated by Django 4.1.3 on 2022-11-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0002_rename_leads_lead_rename_scans_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='grade',
            field=models.CharField(default='F', max_length=2),
        ),
    ]
