# Generated by Django 4.1.3 on 2022-11-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0004_scan_host_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='offers_alerts',
            field=models.BooleanField(default=True),
        ),
    ]
