# Generated by Django 4.1.3 on 2022-12-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0007_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='ip',
            field=models.GenericIPAddressField(primary_key=True, serialize=False),
        ),
    ]
