# Generated by Django 4.1.3 on 2022-12-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0008_alter_scan_date_time_alter_scan_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='scan',
            name='url',
            field=models.URLField(db_index=True, max_length=150, primary_key=True, serialize=False),
        ),
    ]
